techs:
  cuda_animations:
  - - C++14
    - ''
  - - CUDA
    - https://docs.nvidia.com/cuda/archive/10.1/
  - - JavaScript
    - ''
  - - HTML5
    - ''
  cuda_memory_access_recorder:
  - - C++17
    - ''
  - - CUDA
    - https://docs.nvidia.com/cuda/archive/11.1.1
  - - JavaScript
    - ''
  - - HTML5
    - ''
  grpc_url_fetcher:
  - - C++17
    - ''
  - - gRPC
    - https://grpc.io/about/
  - - libcurl
    - https://curl.haxx.se/libcurl/
  lidbox:
  - - Python
    - https://docs.python.org/3.8/
  - - TensorFlow
    - https://www.tensorflow.org/api/r2.3
  parallel_rust_cpp:
  - - C++17
    - ''
  - - Rust
    - https://github.com/rust-lang/rust/tree/1.37.0
  portfolio:
  - - Jinja2
    - https://jinja.palletsprojects.com/en/2.11.x/
  - - HTML5
    - ''
  - - CSS
    - ''
  celerykube:
  - - Python
    - https://docs.python.org/3.8/
  - - Minikube
    - https://github.com/kubernetes/minikube/tree/v1.11.0
  - - Docker
    - https://github.com/docker/cli/tree/v19.03.12
  - - Flask
    - https://flask.palletsprojects.com/en/1.1.x/
  - - Celery
    - https://docs.celeryproject.org/en/v4.4.6/
  code_rain:
  - - Python
    - https://docs.python.org/3.6/
  - - curses
    - https://en.wikipedia.org/wiki/Curses_(programming_library)
  spaghetti_search:
  - - Python
    - https://docs.python.org/3.6/
  - - Flask
    - https://flask.palletsprojects.com/en/0.12.x/
  - - Scrapy
    - https://docs.scrapy.org/en/1.4/
  - - Whoosh
    - https://whoosh.readthedocs.io/en/latest/intro.html
  satellite_routes:
  - - Clojure
    - https://github.com/clojure/clojure/tree/clojure-1.8.0
  - - ThreeJS
    - https://github.com/mrdoob/three.js/tree/r76
  juice_simulator:
  - - C++11
    - ''
  - - LiquidFun
    - https://google.github.io/liquidfun/
  - - SFML
    - https://www.sfml-dev.org/
  graderutils:
  - - Python
    - https://docs.python.org/3.5/
  - - HTML
    - ''
  greedy_string_tiling:
  - - C++14
    - ''
  - - Python
    - https://docs.python.org/3.6/
  debian_version_info:
  - - Python
    - https://docs.python.org/3.7/
  - - HTML
    - ''
  ghht:
  - - Python
    - https://docs.python.org/3.8/
  aoc2020:
  - - Go
    - https://golang.org/doc/go1.15
  robotini_ddpg:
  - - Python
    - https://docs.python.org/3.9/
  - - TensorFlow
    - https://www.tensorflow.org/api/r2.4
  - - TensorFlow Agents
    - https://www.tensorflow.org/agents/api_docs/python/tf_agents

urls:
  cuda_memory_access_recorder:
    github: https://github.com/matiaslindgren/cuda-memory-access-recorder
  cuda_animations:
    github: https://github.com/matiaslindgren/cuda-animations
    demo: https://matiaslindgren.github.io/cuda-animations
  grpc_url_fetcher:
    github: https://github.com/matiaslindgren/grpc-url-fetcher
  lidbox:
    github: https://github.com/matiaslindgren/lidbox
    writing: https://www.isca-speech.org/archive/Interspeech_2020/abstracts/2706.html
  parallel_rust_cpp:
    github: https://github.com/parallel-rust-cpp/shortcut-comparison
    writing: https://parallel-rust-cpp.github.io/
  portfolio:
    github: https://github.com/matiaslindgren/portfolio
  celerykube:
    github: https://github.com/matiaslindgren/celery-kubernetes-example
  code_rain:
    github: https://github.com/matiaslindgren/code-rain
  spaghetti_search:
    github: https://github.com/matiaslindgren/spaghetti-search
  satellite_routes:
    github: https://github.com/matiaslindgren/satellite-routes
    demo: http://satellite-thing.herokuapp.com/
  juice_simulator:
    github: https://github.com/matiaslindgren/JuiceSimulator
  graderutils:
    github: https://github.com/Aalto-LeTech/python-grader-utils
  greedy_string_tiling:
    github: https://github.com/Aalto-LeTech/greedy-string-tiling
  debian_version_info:
    github: https://github.com/matiaslindgren/debian-version-info-app
    demo: https://debian-version-info.herokuapp.com
  ghht:
    github: https://github.com/matiaslindgren/ghht
  aoc2020:
    github: https://github.com/matiaslindgren/AoC2020
  robotini_ddpg:
    github: https://github.com/matiaslindgren/robotini-ddpg

aalto_url: https://www.aalto.fi/en
aalto_msc_thesis: http://urn.fi/URN:NBN:fi:aalto-202006213891
apache_2_license_link: '<a href="http://www.apache.org/licenses/LICENSE-2.0">Apache License, Version 2.0.</a>'
flaticon_link: '<a href="https://www.flaticon.com/" title="Flaticon">flaticon</a>'
roboto_font_link: '<a href="https://fonts.google.com/specimen/Roboto+Slab">"Roboto Slab"</a>'
tiny_font_link: '<a href="https://www.1001fonts.com/tiny-font.html">"Tiny"</a>'
aoc2020_link: '<a href="https://adventofcode.com/2020">Advent of Code 2020</a>'
robotini_racing_simulator_link: '<a href="https://github.com/mikkomultanen/Robotini-Racing-Simulator">Robotini racing simulator</a>'


videos:
  code_rain:
    url: 'https://user-images.githubusercontent.com/11295697/119232718-e92f1a00-bb2e-11eb-9ba8-32842e4d8196.mp4'
    alt: >
      Black screen with vertical columns of random green characters moving downwards at different speeds.
      Mimics the code rain animation seen in the Matrix movies.

  robotini_ddpg_exploring:
    url: 'https://user-images.githubusercontent.com/11295697/119233302-0f55b980-bb31-11eb-931a-aec0a1a19842.mp4'
    alt: >
      Top-down view of the simulator with 6 cars driving mostly correctly,
      occasionally crashing into the wall.

  robotini_ddpg_web_ui:
    url: 'https://user-images.githubusercontent.com/11295697/119233343-36ac8680-bb31-11eb-8fbf-e9f71f8e90d6.mp4'
    alt: >
      Web user interface showing 4 changing JSON dumps of training state and
      a live feed from 4 car cameras during exploration.
